### ISSUE TITLE
Please consider adding TransferFrom event in Token.sol

### ISSUE THREAD

**Issue by simondlr** [slockit/smart-contract#15]
Hi. Minor change that will help dapps recreate state of the token fully using only events.

https://github.com/ethereum/EIPs/issues/20#issuecomment-176463861

**Comment by CJentzsch** [comment]
@simondlr is this resolved in the current standard?
Happy to use with whatever you come up with as a standard. But I need to finalize my contracts (actually within this week) in order to enter the last testing period with a fixed bytecode.

**Comment by simondlr** [comment]
@CJentzsch It's resolved, yes. Sorry. I was trying to get more people in on the discussions by pushing it. I'll be more prudent in the future & only push these once fully confirmed by the community.

For the default standard, we are good for now.

**Comment by CJentzsch** [comment]
@simondlr Can you link me to the default standard (or is my implementation: https://github.com/slockit/smart-contract/blob/master/Token.sol
already a correct implementation of the standard?

**Comment by simondlr** [comment]
@CJentzsch this is what we use for tokens in all our internal projects atm: https://github.com/ConsenSys/Tokens/blob/master/Token_Contracts/contracts/Standard_Token.sol

The code looks good. I'm wondering whether it's a good idea to collapse transfer & transferFrom together? It's more elegant, definitely, but it introduces extra gas costs that over time will end up more than the savings for deployment costs. Slock.it isn't going to be deploying many token contracts. Thus you should probably optimise for gas savings for each function, rather than gas savings per contract deployment?

It's very small, but the extra ifs (only costing like 200-400 gas or something) ends up with more costs which all the users have to foot/pay for. Very small, but will over time add up. :)

It also means that in the event that you approve yourself some funds (edge case), you won't be able to reduce allowance to yourself (when _from == msg.sender). For example:

A.approve(A, 100)
A.transferFrom(C, 50)

msg.sender = A
from = A
to = C

In this scenario, your allowance to yourself won't be reduced. This is a super edge case and I'm not ever sure why one would do this, but just something to consider. :)

You also aren't implementing totalSupply() btw. And how are tokens created?

**Comment by CJentzsch** [comment]
@simondlr 
I agree with the gas costs, I can change that back, just wanted to remove code duplication.
I implemented totalSupply by making it public: https://github.com/slockit/smart-contract/blob/master/Token.sol#L44
There is no constructor since we will not premine tokens.
They are created by the contracts which derives from it: https://github.com/slockit/smart-contract/blob/master/Crowdfunding.sol#L78-L79

**Comment by simondlr** [comment]
Oh I see. Great! Excited for the release. Lemme know if I can help with anything else. :clap:

**Comment by CJentzsch** [comment]
Thanks a lot! I am about to write a lot of tests. Have you test which I can reuse for the Token contract?

**Comment by simondlr** [comment]
@CJentzsch yes. Made some basic ones using Truffle's Mocha testing (using ethereumjs testrpc as back-end).

https://github.com/ConsenSys/Tokens/blob/master/Token_Contracts/test/standardToken.js

If you use this and add more general tests, would love to add them.
