### ISSUE TITLE
potential bug in the slockdao contract

### ISSUE THREAD

**Issue by ResourceHog** [slockit/smart-contract#6]
wouldn't the following line of code in slockdao.sol result in slockit receiving nothing?
basically totalWeiRecieved would be set to 0 the first time the function containing this line is called.
resulting in msg.sender receiving nothing. I am confused about the if statement. I assume that it would return true. either way msg.sender.send() is executed before totalWeiRecieved is set.
after which totalweirecieved is set to the balance of the contract.

the result being that slock doesn't receive the crowdfunded money.

Is my reasoning correct?

>    function finalize() external
    {
        if (now > closingTime && msg.sender == 0x510c && totalWeiReceived == 0 && this.balance >= minValue)
        {
            if (msg.sender.send(totalWeiReceived)) totalWeiReceived = this.balance;
        }
    }

**Comment by CJentzsch** [comment]
Your are right. Fixed the bug. Thanks!
But this contract is deprecated. This is only a crowdfunding contract and not a real DAO. Since we are still discussing the rules of the DAO I stopped updating/maintaining the contract until the rules are finalized. When everything is done, I will call for review.

**Comment by ResourceHog** [comment]
Are you guys discussing that at the slack? I am kind of hoping to get an invite and participate. XD

**Comment by CJentzsch** [comment]
Just sign up for the mailing list on our website and you get an invite
