### ISSUE TITLE
Sec Issue Utlize token transfer to allow infinite voteing.

### ISSUE THREAD

**Issue by colm** [slockit/smart-contract#8]
I believe that a malicious user could utilize the transfer functionality in line 100 of Token.sol to transfer their tokens to another account after they have voted once. 

Since function vote line 201 or DAO.sol prevents a double vote by checking a list of voters for msg.sender the new owner with a different address could vote again. 

This could allow a malicious user to have potentially infinite votes on any proposal.

**Comment by CJentzsch** [comment]
This is prevented by taking the `voteWeight` at the time of execution.
So when you vote for something, but then transfer your tokens, your vote is worth nothing:
https://github.com/slockit/smart-contract/blob/master/DAO.sol#L224

**Comment by colm** [comment]
Oh yes. thanks for that. I'll keep poking around and let you know if i find anything else.

**Comment by CJentzsch** [comment]
Thanks a lot for your help!

**Comment by stephantual** [comment]
Thanks a lot @colm !

**Comment by colm** [comment]
No problem. I am glad it is useful. I saw you merged my pull request. I will add some more tests as I explore the contract more :)
